### ISSUE TITLE
Lepida Autentication

### ISSUE THREAD

**Issue by mattiarainieri** [WPGov/wp-spid-italia#14]
Buongiorno,
Noto che dai provider di autenticazione non è presente Lepida; verrà implementato?

Grazie mille per il lavoro svolto, cordiali saluti

**Comment by milesimarco** [comment]
Buongiorno Mattia,l'ultima versione attualmente disponibile su GitHub include già il supporto per Lepida. Se così non fosse potrebbe esserci qualche conflitto o malfunzionamento, in tal caso mi servirebbe il link per poter verificare.Grazie e Cordiali SalutiMarcoIl 11 set 2021 12:44, mattiarainieri ***@***.***> ha scritto:

Buongiorno,

Noto che dai provider di autenticazione non è presente Lepida; verrà implementato?

Grazie mille per il lavoro svolto, cordiali saluti
