### ISSUE TITLE
Check lunghezza campi dei

### ISSUE THREAD

**Issue by pkirk** [WPGov/wp-spid-italia#16]
Gentili, vi segnalo che ci siamo imbattuti in un problema di CSR non generato da parte della funzione openssl_csr_new del PHP, che restituiva false:
`$csr = openssl_csr_new($dn, $privkey, array('digest_alg' => 'sha256'));`
nel file lib/src/Spid/Saml/SignatureUtils.php

Il tutto perché su sp_org_name nelle impostazioni
/wp-admin/options-general.php?page=spid_menu&spid_action=option
avevamo sforato i 64 caratteri.

Vi suggerirei quindi un controllo di lunghezza lato admin. Per gli altri campi del DN sembra esserci un parametro di lunghezza massima nel file openssl.cnf .

**Comment by milesimarco** [comment]
Buongiorno @pkirk,
lo spunto è stata integrato nel codice, tramite semplice validazione del campo nativa in html.

Grazie per la segnalazione,
M.
