### ISSUE TITLE
Richiesta Metadata rifiutata

### ISSUE THREAD

**Issue by Verbavolant37** [WPGov/wp-spid-italia#24]
Buongiorno,
riporto la risposta di spid.tech@agid.gov.it alla richiesta di aggiunta del Metadata descritta al punto 3: Proceduta tecnica

---
Salve,

in risposta alla vostra email, riportata di seguito, vi informiamo che la domanda di aggiornamento del metadata è stata respinta in quanto il vostro metadata non ha superato i controlli: come da Regole Tecniche, l'EntityID è l'attributo che identifica univocamente il Service Provider, quindi è necessario che sia sempre lo stesso in ogni aggiornamento dello stesso metadata.

N.B. Ogni ente può avere un solo metadata pertanto se è un aggiunta di un nuovo servizio va creato in unico file xml contenente tutti i servizi. Qual'ora si volesse sostituire l'entityID va specificato nella mail. Questo comporta la dismissione del precedente da tutti gli IDP.

Tutti i test delle response falliscono.
---

Non capisco cosa intendono, il metadata l'ho copiato come descritto nella guida

Grazie
Jacopo

**Comment by milesimarco** [comment]
Buonasera,
verifichi la corretta compilazione dei dati e che con l'ambiente demo il flusso di accesso funzioni.

Se ciò non dovesse funzionare, può inviarmi l'url del metadata tramite email per una verifica.

Cordiali Saluti

Marco
