### ISSUE TITLE
Custom login address

### ISSUE THREAD

**Issue by milesimarco** [WPGov/wp-spid-italia#27]
Buongiorno @milesimarco 

AGID ha risposto così: tutti i test delle response si atterra su https://meroni.edu.it/wp-login.php?spid_sso=in con il messaggio "Please check entered address and try again or go to homepage".

Cosa intendono?
L'indirizzo di login che ho segnalato all'interno della mail è https://meroni.edu.it/login/.

_Originally posted by @fedeanimation in https://github.com/WPGov/wp-spid-italia/issues/24#issuecomment-992249446_

**Comment by milesimarco** [comment]
Buonasera @fedeanimation,
il plugin attualmente non è direttamente compatibile con moduli di login terze parti.

Quale sistema state utilizzando per personalizzare l'indirizzo di accesso? /login anziché /wp-login.php

**Comment by fedeanimation** [comment]
Buongiorno @milesimarco

stiamo usando il plugin WPS Hide Login che ci serve per evitare di subire gli attacchi automatici verso wp-admin e wp-login.

**Comment by milesimarco** [comment]
Buongiorno,
con la versione 2.3.1 è stato integrato il rilevamento automatico di indirizzi di login custom.
Il funzionamento con WPS Hide Login ha avuto test positivi. 

In aggiunta all'automatismo sono stati integrati filtri ulteriori per sviluppatori.

Marco Milesi
