### ISSUE TITLE
Problema di sessione nella funzione del filtro "login_message"?

### ISSUE THREAD

**Issue by davidemerlitti** [WPGov/wp-spid-italia#29]
Salve,

sto tentando di far funzionare il plugin su questo sito web:

https://dev.informaticaumanistica.com/wp-partigiani

che è una versione di sviluppo e test di un sito di ICAR- MiC già in produzione:

https://www.partigianiditalia.beniculturali.it/

La pagina di login standard è questa:

https://dev.informaticaumanistica.com/wp-partigiani/wp-login.php

Credo sia tutto configurato correttamente tuttavia cercando di fare il login usando l'identity provider demo e le credenziali di un utente di livello 1 (lucrezia/password123 ad esempio) succede che la funzione isAuthenticated() della classe Saml trova $_SESSION vuoto e quindi restituisce false (ho seguito il codice con un debugger passo-passo).

Ho già controllato se altri plugin o temi attivi manipolano la session php ma non ho trovato niente di strano.

Stampando il contenuto di $_SESSION in un file di log dentro la funzione authnRequest() della classe Idp ottengo questo:

<pre>
2022-01-12 16:40:29 $_SESSION=Array
(
    [RequestID] => _237a1c092eedfc84b4c856af37447948
    [idpName] => idp_demo
    [idpEntityId] => https://demo.spid.gov.it
    [acsUrl] => https://dev.informaticaumanistica.com/wp-partigiani/login/?spid_sso=in
)
</pre>

e sembra ok. Ma dentro isAuthenticated() della classe Saml, chiamata subito dopo, $_SESSION è vuoto.

Qualche idea su quale possa essere il problema? Grazie

-- 
Davide Merlitti

**Comment by davidemerlitti** [comment]
@milesimarco  dopo un po' di test su altri browser ho scoperto che il problema si verifica solo usando una finestra anonima di Chrome probabilmente a causa del fatto che tra varie chiamate si perde il cookie che consente di mantenere la sessione php.
Possiamo considerare chiuso il problema. Non si tratta di un bug. Grazie.

**Comment by milesimarco** [comment]
Grazie per il feedback!
