### ISSUE TITLE
Erorri durante installazione certificati

### ISSUE THREAD

**Issue by astrain01** [WPGov/wp-spid-italia#3]
Ciao,
ho una serie di problemi quando tento di installare il plugin. 
Lo sto installando su un sito locale ospitato su XAMPP. Riuscite a darmi supporto?
In allegato l'immagine degli errori che mi si sono presentati.
Ho cercato di impostare il sito su https ma il risultato non è cambiato.

Grazie a tutti.
![inst_err](https://user-images.githubusercontent.com/37105253/37030453-5344bcb0-213b-11e8-93e9-361439450844.PNG)

**Comment by milesimarco** [comment]
Ciao @astrain01,
sotto Windows il plugin non è testato e genera alcuni problemi, tra cui quello da te indicato. Hai modo di testarlo online su un server Linux?
