### ISSUE TITLE
Provincia non valida

### ISSUE THREAD

**Issue by fedeanimation** [WPGov/wp-spid-italia#30]
Buongiorno @milesimarco 

Tramite lo SPID validator ho questo errore:

`failure - value: ('error parsing asn1 value: ParseError { kind: InvalidValue, location: ["RawCertificate::tbs_cert", "TbsCertificate::serial"] }',)`

La provincia di dove si trova la scuola è Monza e Brianza.

**Comment by milesimarco** [comment]
Buongiorno,
verifichi che in **Impostazioni -> SPID -> Impostazioni** sia tutto compilato.

In caso di persistenza dell'errore le chiedo di inviarmi il link del metadata XML: [https://www.wpgov.it/contatti/](https://www.wpgov.it/contatti/)
