### ISSUE TITLE
Spid azienda privata

### ISSUE THREAD

**Issue by giovanisoluzioni** [WPGov/wp-spid-italia#31]
Buongiorno,
volevo sapere se è possibile, utilizzando questo plugin, implementare l'accesso con lo Spid su un sito privato e quindi non della PA.

Grazie

**Comment by milesimarco** [comment]
Buongiorno,
confermo che il plugin può essere agevolmente utilizzato anche per casi di privati, richiede alcune modifiche tramite filtri che sono in corso di refactoring per essere gestite da backend di WordPress.

Tenga presente che l'adesione al servizio è vincolata alla sottoscrizione di un contratto con Agid e a un costo di servizio.

Rif. https://www.spid.gov.it/cos-e-spid/diventa-fornitore-di-servizi/
Rif. costi https://www.agid.gov.it/sites/default/files/repository_files/allegato_4_dt_166_corrispettivi_spid_idp_2019_0.pdf
