### ISSUE TITLE
HTTP Status 403 PosteID

### ISSUE THREAD

**Issue by matteonespoli** [WPGov/wp-spid-italia#34]
Buongiorno e complimenti per l'applicativo.

Testando con PosteID il login la prima autenticazione va sempre a buon fine.
Purtroppo, dal secondo login (dopo la scansione del QR) spesso e volentieri appare l'errore "HTTP Status 403 – Forbidden" di poste o l'errore WP "SPID - Riprovare".

Grazie!

**Comment by amdounio** [comment]
Hello , 

Thanks you for this plugin , but i have the same problem , i login via spid in the second try 

"SPID - Riprovare" in the first try ,
