### ISSUE TITLE
Login e registrazione con SPID

### ISSUE THREAD

**Issue by HshMatera** [WPGov/wp-spid-italia#35]
Buongiorno a tutti, 
posto questa soluzione per il problema della registrazione utente wordpress passando per l'autenticazione SPID e del login con utenza già presente. Ho testato tutto con il validator e utente demo di AGID. 
Nel file wp-spid-italia.php del plugin ho modificato questa porzione di codice: 
`if ( empty( $user ) ) {
                $users = get_users(
                    array(
                        'meta_key' => 'codice_fiscale',
                        'meta_value' => $cf,
                        'number' => 1,
                        'count_total' => false,
                    )
                );
                if ( !empty( $users ) ) {
                    $user = reset( $users );
                } else {
                    apply_filters( 'spid_registration_filter_new_user', $attributes );
                }
            }
            if ( !is_wp_error( $user ) && !empty( $user ) ) {
                
                apply_filters( 'spid_registration_filter_existing_user', $attributes, $user );
                
                spid_update_user( $user, $attributes );

                wp_clear_auth_cookie();
                wp_set_current_user ( $user->ID );
                wp_set_auth_cookie  ( $user->ID );
            
                wp_safe_redirect( apply_filters( 'spid_registration_default_login_redirect', admin_url() ) );
                exit();`
con questa:
`// SE USER E' VUOTA
            if ( empty( $user ) ) {
				
                $users = get_users(
                    array(
                        'meta_key' => 'codice_fiscale',
                        'meta_value' => $cf,
                        'number' => 1,
                        'count_total' => false,
                    )
                );
                if ( !empty( $users ) ) {					
                    $user = reset( $users );
                } else {
									
					    $user = wp_insert_user( array(
					    'user_login' => strtolower($attributes['familyName']),
						'last_name' => $attributes['familyName'],
						'user_email' => $attributes['email'],
						'first_name' => $attributes['name'],
						'display_name' => $attributes['name']
					));

					update_user_meta($user, 'codice_fiscale' , $cf);
					
					wp_clear_auth_cookie();                
				wp_set_current_user($user);
				wp_set_auth_cookie($user);
				          
                wp_safe_redirect( apply_filters( 'spid_registration_default_login_redirect', admin_url() ) );
				
                exit();
		
                }
				
            }
			// SE USER E' PIENA E SENZA ERRORI			
            if ( !is_wp_error( $user ) && !empty( $user ) ) {     		
							
				wp_clear_auth_cookie();                
				wp_set_current_user ( $user->ID );
                wp_set_auth_cookie  ( $user->ID );
				          
                wp_safe_redirect( apply_filters( 'spid_registration_default_login_redirect', admin_url() ) );
				
                exit();`
dove nella prima parte (se non è presente un utente) procedo con la registrazione 'wp_insert_user' mentre se è presente eseguo la login.

Spero di essere stato utile per qualcuno. Se avete delle migliorie è bene usare questo mezzo per condividerle.

Ciao

**Comment by milesimarco** [comment]
Grazie @HshMatera,
ogni contributo è sempre ben accetto! Ad oggi, considerata l'elevata differenza di gestione delle registrazioni da portale a portale (es. ruoli o attributi extra di plugin terze parti), la strada di integrazione consigliata è tramite il filtro indicato.

A presto,
Marco

**Comment by HshMatera** [comment]
@milesimarco ho apportato delle modifiche al codice del plugin proprio perchè il filtro indicato per l'integrazione non funziona. Non esegue la nuova registrazione se l'utente non è già inserito nel database di wordpress.
