### ISSUE TITLE
Impossibile inserire sp_org_name completo

### ISSUE THREAD

**Issue by unosrl** [WPGov/wp-spid-italia#37]
Buongiorno,
in base al limite di 60 caratteri del campo **sp_org_name** non è possibile inserire il nome completo dell'ente a cui stiamo dando supporto.

Aggirando il limite, il file crt risultante è di 0 bytes e nei log di php appare il seguente errore:

> PHP Warning:  openssl_csr_new(): dn: add_entry_by_NID 17 -> _nome_ente_ (failed; check error queue and value of string_mask OpenSSL option if illegal characters are reported)

Come dobbiamo procedere in questo caso?

Grazie,
Cordiali saluti

**Comment by milesimarco** [comment]
Buonasera @unosrl,
non essendoci vincoli particolari consiglierei di ricorrere a leggere abbreviazioni per aggirare il limite.

A presto,
Marco
