### ISSUE TITLE
Possibilità di restringere la login con spid ad un bacino di utenti

### ISSUE THREAD

**Issue by JEricaM** [WPGov/wp-spid-italia#40]
Buongiorno

Scrivo in merito ad una domanda riguardante le funzionalità del plugin. 
Avrei necessità di valutare l'integrazione del plugin su un eventuale sito di una PA.

E' possibile col plugin restringere l'accesso a solo certi utenti? ecco il caso in maggior dettaglio.
sito PA di un ordine di architetti, avrei bisogno di permette tramite spid l'accesso ai soli architetti iscritti all'albo degli architetti, e non a tutti coloro che possiedono lo spid.
e' possibile? ovviamente faccio riferimento anche alla possibilità che sia necessario dello sviluppo di codice custom di controllo dell'utente a seguito della login. mi chiedevo infatti principalmente se il plugin avesse modo di trasmettere questo tipo di informazioni.

 ho guardato tutta la documentazione e non ho trovato personalizzazioni di questo tipo, ma volevo essere sicura di ciò.

Grazie in anticipo

**Comment by milesimarco** [comment]
Buongiorno @JEricaM,
by-default, il plugin autentica solo gli utenti già profilati sul portale WordPress (in questo caso, se avete una lista di architetti abilitati o abilitabili al servizio, potete importarla come utenti). In questo caso non sarebbe richiesta alcuna modifica custom.

In alternativa, possono essere impostati dei filtri proprio per inibire la registrazione degli utenti qualora non rispettassero alcune regole (es. appartenenza a una lista in WP o verifiche via API).

Confermo dunque la fattibilità, sia con quanto offerto out of the box, sia con la possibilità di customizzare la logica tramite filtri via php.

Qualora fossero necessarie ulteriori informazioni resto a disposizione.
A presto,
Marco M

**Comment by JEricaM** [comment]
@milesimarco 
Ti ringrazio per l'esaustiva e celere risposta, era proprio quello che speravo di leggere.

Grazie e buona giornata
Erica

**Comment by milesimarco** [comment]
Aggiungo: nel caso _out of the box_, la corretta autenticazione avviene se in WP è già registrato un utente con la stessa email o con lo stesso codice fiscale del profilo SPID, altrimenti fallisce.
