### ISSUE TITLE
Reinstallazione sito con SPID

### ISSUE THREAD

**Issue by vitolamacchia** [WPGov/wp-spid-italia#45]
Sono costretto a installare nuovamente il sito WordPress su cui c'è già l'accesso a SPID.
Posso inserire i certificati e dati sul nuovo?
Come?
Attendo consigli a riguardo

**Comment by milesimarco** [comment]
Buongiorno @vitolamacchia,
il plugin genera alcuni file all'interno di wp-content/spid che andranno necessariamente mantenuti nel nuovo spazio (insieme alle impostazioni del plugin e alla chiave univoca assegnata al sito dal plugin. Consiglio backup preventivo di tutto l'ambiente in modo da poter effettuare rollback in caso di problemi.
**Il portale WordPress sarà installato da zero o ripristinato da un backup?**
Non mi sono note anomalie ma in caso di problemi resto a disposizione, essendo uno use-case potenzialmente utile anche per altri colleghi.
A presto,
Marco
