### ISSUE TITLE
Come usare il validatore di test/demo per verificare il funzionamento?

### ISSUE THREAD

**Issue by IlPizza79** [WPGov/wp-spid-italia#49]
All'inizio della sezione 3 della documentazione (Procedura tecnica) c'è scritto di "verificare che l'autenticazione funzioni correttamente con il validatore di test/demo".

Però non è ben spiegato cosa dovrei fare per fare un test, né quali opzioni dovrei attivare per poter fare un test. Ad esempio:

- devo attivare l'opzione "Abilita Validatore" e lasciare "Abilita Login SPID" disattivata?
- devo attivare entrambe le opzioni?
- se lascio entrambe le opzioni attivate vedo il pulsante "Entra con SPID" nel login di Wordpress, ma comunque l'accesso con SPID non funziona.

Quindi, cosa dovrei fare di preciso per verificare se l'autenticazione funziona? Posso comunque andare avanti con la procedura tecnica o è strettamente necessario fare prima questa verifica?

Grazie in anticipo!

**Comment by milesimarco** [comment]
Buongiorno,
occorre usare l'IDP "Idptest" per fare le prove.

Al seguente link possono essere recuperate le utenze di test: https://demo.spid.gov.it/

La verifica non è vincolante per procedere con la procedura tecnica ma caldamente consigliata per effettuare dovute verifiche accertandosi che il flusso sia corretto e che non ci siano conflitti.

NB.
- Abilita login SPID consente di accendere/spegnere il plugin
- Abilita validatore consente di effettuare le procedure di test e va tenuto attivo fino all'esito positivo del collaudo tecnico
- L'accesso a Spid con gli IDP reali non funzionerà fino a quando il collaudo tecnico non sarà effettuato

**Comment by IlPizza79** [comment]
Buongiorno Marco,
grazie mille per la risposta, proverò a fare il test seguendo la procedura che hai descritto.

Ne approfitto per un'altra domanda: il plugin WP SPID funziona solo con il form di login predefinito di Wordpress oppure è possibile integrarlo anche con form di login gestiti da plugin di terze parti? Nel caso, sarà possibile richiedere un'integrazione personalizzata, anche a pagamento?

Grazie!

**Comment by Zhigalin** [comment]
Buongiorno @milesimarco 
Stranamente l'Idptest da errore nonostante il collaudo da AGID e' stato superato e la verifica con
l'ultima versione di spid-saml-check da tutto verde.
Sa di cosa potrebbe trattarsi?
![image](https://github.com/WPGov/wp-spid-italia/assets/8227915/b0ada7fe-0b95-4519-b10e-3fb7b1f643b4)
