### ISSUE TITLE
Login senza esito

### ISSUE THREAD

**Issue by datanetsrl** [WPGov/wp-spid-italia#5]
Salve,
stiamo testando il plugin per eseguire il login attraverso lo SPID.

Da alcuni test abbiamo notato che se l'utenza non è presente in archivio, si viene reindirizzati in home ma senza alcun messaggio. Non sarebbe opportuno inserire un alert che informi l'utente che il suo account non è presente in archivio?

Saluti

**Comment by milesimarco** [comment]
Buongiorno @datanetsrl 
ho rilasciato la versione 1.4 con l'alert di aggiunta (il redirect ora ritorna alla pagina di login e non più alla homepage).

A presto
Marco

**Comment by datanetsrl** [comment]
Grazie mille per il celere update.

Volevamo inoltre chiederti se il check del login avviene solo su corrispondenza email o anche CF.
Abbiamo creato un'utenza su wp ed inserito cf, ma eseguendo login SPID appare il messaggio di errore.

Saluti
