### ISSUE TITLE
Errori SPID Validator

### ISSUE THREAD

**Issue by AlfioCostanzo** [WPGov/wp-spid-italia#52]
Buongiorno @milesimarco,
abbiamo notato che in fase di validazione del metadata generato, otteniamo degli errori con il "Check per Produzione" attivato.

Alleghiamo screen

![image](https://github.com/WPGov/wp-spid-italia/assets/84495915/cb061fab-edf4-4034-ae8d-55bebd2a1ab7)

Questo potrebbe comportare il NON superamento del collaudo?

Grazie,
Alfio

**Comment by milesimarco** [comment]
Buongiorno @AlfioCostanzo,
alcuni errori non sono bloccanti. Nel caso specifico non ne ho evidenza, dunque procederei comunque con la richiesta di collaudo.
