### ISSUE TITLE
Provider SPID non diposnibili

### ISSUE THREAD

**Issue by iana63** [WPGov/wp-spid-italia#59]
Salve, con versione 2.2.4 ho notato che alcuni nuovi gestori SPID (IO INTESI GROUP e EtnaID) non vengono proposti. C'è una soluzione ?

**Comment by milesimarco** [comment]
Buongiorno @iana63,
l'unica versione in supporto è l'ultima (v2.7.1) che include tutti i provider. Qualora fosse necessario applicare la modifica a una versione precedente dovrà essere fatto manualmente verificando le modifiche del codice del plugin.

Cordialmente,
M.
