### ISSUE TITLE
where is declarated filter 'spid_registration_filter_new_user'

### ISSUE THREAD

**Issue by alessandrozou** [WPGov/wp-spid-italia#72]
In the process for authentication is present the line $user = apply_filters( 'spid_registration_filter_new_user', $attributes );

Where is the declaration of the filter 'spid_registration_filter_new_user'?

**Comment by milesimarco** [comment]
Hi @alessandrozou,
you can find some use-cases and examples here:

- https://github.com/WPGov/wp-spid-italia/issues/26
- https://github.com/WPGov/wp-spid-italia/issues/35

The filter is intended for further customization by the user, so you can attach your own logic by adding your actions (using a custom plugin or theme functions.php, for example).

Best regards,
M.
