### ISSUE TITLE
Errore con SimpleSAML Login

### ISSUE THREAD

**Issue by assistenzanet** [WPGov/wp-spid-italia#8]
Quando da Backend provo a cliccare su simpleSAML ottengo un errore 500 e dai log del server vedo il seguente errore:
PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in ....

**Comment by angeloagus** [comment]
Io ho il medesimo errore.
Ho un portale web in macchine virtuali su Microsoft Azure, le macchine virtuali hanno Ubuntu 18.04 con PHP e WordPress per la parte web.
All'installazione del PlugIn e all'attivazione non mi ha segnalato nessun errore.
Quando vado nel tab SimpleSaml login vengo rediretto sulla pagina HTTP500.
nel php_error.log viene indicata l'impossibilità di trovare il driver SQL.php ma in realtà da ulteriori analisi ho rilevato che non vengono create correttamente le stringhe di collegamento al DB.
Preciso che il DB è configurato esternamente all'applicazione

php_error.log:
[29-Apr-2021 11:50:57 Europe/Rome] PHP Fatal error:  Uncaught PDOException: could not find driver in D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Store\SQL.php:54
Stack trace:
#0 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Store\SQL.php(54): PDO->__construct('sqlite:D:\\home\\...', NULL, NULL)
#1 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Store.php(49): SimpleSAML_Store_SQL->__construct()
#2 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\SessionHandler.php(121): SimpleSAML_Store::getInstance()
#3 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\SessionHandler.php(39): SimpleSAML_SessionHandler::createSessionHandler()
#4 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Session.php(155): SimpleSAML_SessionHandler::getSessionHandler()
#5 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Session.php(410): SimpleSAML_Session->__construct(true)
#6 D:\home\site\wwwroot\wp-content\ in D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Store\SQL.php on line 54
[29-Apr-2021 12:04:54 Europe/Rome] PHP Fatal error:  Uncaught PDOException: could not find driver in D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Store\SQL.php:54
Stack trace:
#0 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Store\SQL.php(54): PDO->__construct('sqlite:D:\\home\\...', NULL, NULL)
#1 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Store.php(49): SimpleSAML_Store_SQL->__construct()
#2 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\SessionHandler.php(121): SimpleSAML_Store::getInstance()
#3 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\SessionHandler.php(39): SimpleSAML_SessionHandler::createSessionHandler()
#4 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Session.php(155): SimpleSAML_SessionHandler::getSessionHandler()
#5 D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Session.php(410): SimpleSAML_Session->__construct(true)
#6 D:\home\site\wwwroot\wp-content\ in D:\home\site\wwwroot\wp-content\plugins\wp-spid-italia\lib\lib\SimpleSAML\Store\SQL.php on line 54
